### ISSUE TITLE
Trouble with 7.0.10-26 install today 

### ISSUE THREAD

**Issue by Jmuccigr** [blogabe/homebrew-xplanet#23]
==> Upgrading 1 outdated package:
blogabe/xplanet/imagemagick 7.0.10-25 -> 7.0.10-26
==> Upgrading blogabe/xplanet/imagemagick 7.0.10-25 -> 7.0.10-26 --with-fftw --with-libheif --with-libwmf --wi
==> Downloading https://dl.bintray.com/homebrew/mirror/ImageMagick-7.0.10-26.tar.xz
==> ./configure --disable-osx-universal-binary --prefix=/usr/local/Cellar/imagemagick/7.0.10-26 --disable-opencl --enabl
==> make install
Last 15 lines from /Users/john_muccigrosso/Library/Logs/Homebrew/imagemagick/02.make:
  "_gzputc", referenced from:
      _WriteBlob in libMagickCore_7_Q16HDRI_la-blob.o
  "_gzread", referenced from:
      _ReadBlob in libMagickCore_7_Q16HDRI_la-blob.o
  "_gzseek", referenced from:
      _IsBlobSeekable in libMagickCore_7_Q16HDRI_la-blob.o
      _SeekBlob in libMagickCore_7_Q16HDRI_la-blob.o
  "_gztell", referenced from:
      _TellBlob in libMagickCore_7_Q16HDRI_la-blob.o
  "_gzwrite", referenced from:
      _WriteBlob in libMagickCore_7_Q16HDRI_la-blob.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [MagickCore/libMagickCore-7.Q16HDRI.la] Error 1
make: *** [install] Error 2

**Comment by blogabe** [comment]
Apologies for delay @Jmuccigr Can you try again. Just updated ImageMagick to ImageMagick-7.0.10-29

**Comment by Jmuccigr** [comment]
Yep, works fine. Thanks.
